name=DevLabDDP
version=1.0.1
author=UNIT Electronics
maintainer=Adrian Rabadan, Cesar Bautista, Jonathan Mejorado, Fernando Flores
sentence=Arduino master for the DevLab Device Protocol.
paragraph=Discovers, validates and communicates with DDP I2C devices.
category=Communication
url=https://github.com/UNIT-Electronics-MX/unit_devlab_ddp_library
architectures=*
includes=DevLabDDP.h,DevLabDDPConsole.h
